
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-3
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2Njg0NTE2","is_bot":false,"login":"khtran1","name":"Kenny Tran"},"headRefName":"Kenny-UpdateREADME","number":28,"title":"Update README.md","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/28"},{"author":{"id":"MDQ6VXNlcjU5NzkwNjQ0","is_bot":false,"login":"zihaoxu20010109","name":"Hardy Xu"},"headRefName":"Hardy-GradeHistoryController","number":26,"title":"hx - grade history controller and related service files","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/26"},{"author":{"id":"U_kgDOBXRUhw","is_bot":false,"login":"nickzahlis","name":""},"headRefName":"Nick-FixAnthSearchBug","number":23,"title":"Bug Fix - Search function doesn't work on default subject without switching from another 7pm-3","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/23"},{"author":{"id":"MDQ6VXNlcjQ5OTAyNTkx","is_bot":false,"login":"KaneD985","name":"Kane Deng"},"headRefName":"Kane-NavbarImprovement","number":22,"title":"Navbar improvement","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/22"},{"author":{"id":"MDQ6VXNlcjU5NzkwNjQ0","is_bot":false,"login":"zihaoxu20010109","name":"Hardy Xu"},"headRefName":"Hardy-HistoryBackend","number":21,"title":"hx - added history eneity and repository","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/21"},{"author":{"id":"MDQ6VXNlcjc3NDA1OTEx","is_bot":false,"login":"wq12li","name":""},"headRefName":"Yiu-Shing-InstructorBackend","number":18,"title":"Implement backend endpoint for search by instructor","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/18"}]
