
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-3
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"Ishaan-FixBugButtonWhereCoursesNotExpandable-pc-testing","number":58,"title":"in/pc - remove +/- where not needed from basic course search and storybook for SectionTableBase","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/58"},{"author":{"id":"MDQ6VXNlcjQ5OTAyNTkx","is_bot":false,"login":"KaneD985","name":"Kane Deng"},"headRefName":"Kane-ErrorMessages","number":57,"title":"Kane - Add error message when the input course is not found in the database, edit the table showing-up logic","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/57"},{"author":{"id":"MDQ6VXNlcjg2Njg0NTE2","is_bot":false,"login":"khtran1","name":"Kenny Tran"},"headRefName":"Kenny-RoomSearchFrontendIndex","number":51,"title":"kt - Add files for index page (Building Search 3/3)","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/51"},{"author":{"id":"MDQ6VXNlcjg2Njg0NTE2","is_bot":false,"login":"khtran1","name":"Kenny Tran"},"headRefName":"Kenny-RoomSearchFrontendForm","number":50,"title":"kt - Add files for form component (Building Search 2/3)","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/50"}]
